---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: centos-6.4_chef-11.4.4
  driver_config: 
    box: opscode-centos-6.4_chef-11.4.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: default
  run_list:
    - recipe[ktc-testing]
    - recipe[ktc-etcd]
    - recipe[sensu::default]
    - recipe[collectd::client]
    - recipe[ktc-openstack-ha]
  attributes:
    etcd:
      args: '-c 127.0.0.1:4001 -s 127.0.0.1:7001'
      servers:
        - 127.0.0.1
    ha_disabled: true
    openstack:
      developer_mode: true 
    vips:
      tags:
        api: 10.0.2.50

- name: ha_db
  run_list:
    - recipe[ktc-testing]
    - recipe[ktc-etcd]
    - recipe[ktc-openstack-ha::mysql]
  attributes:
    etcd:
      args: '-c 127.0.0.1:4001 -s 127.0.0.1:7001'
      servers:
        - 127.0.0.1
    ha_disabled: true
    openstack:
      developer_mode: true
    vips:
      tags:
        mysql: 10.0.2.50
